services:
  app:
    image: hwangrock/modam:latest

    ports:
      - "8080:8080"

    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      ALADIN: ${ALADIN}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
